# Generated by Django 5.0.6 on 2025-02-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryorder_deliverystatusupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='artist_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='artist_pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='customer_pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
