# Generated by Django 5.0.6 on 2025-02-05 04:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='invalid_pincode', message='Pincode must be 6 digits', regex='^[0-9]{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_details', to='accounts.artist')),
            ],
        ),
    ]
