# Generated by Django 5.0.6 on 2025-02-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_shippingaddress_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='face_registered',
            field=models.BooleanField(default=False),
        ),
    ]
