# Generated by Django 5.0.6 on 2025-03-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_customers_face_encoding_customers_face_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='face_encoding',
            field=models.TextField(null=True),
        ),
    ]
